version: "2.1"

services:
  tugboat: &tugboat_base
    build: './host'
    tty: true
    command: ["roslaunch", "tugboat", "tugboat_empty_world.launch"]
    privileged: true
    ports:
      - 11312:11312
    environment: &tugboat_environment
      TURTLEBOT3_MODEL: 'burger'
      GAZEBO_MASTER_URI: tugboat:11312
      DISPLAY: ':0'
    volumes: &tugboat_volumes
      - /Users/airhorns/Code/tugboat/tugboat:/root/catkin_ws/src/tugboat:delegated

  roscore:
    <<: *tugboat_base
    command: ["roscore", "-v"]
    ports:
      - 11311:11311

  # This container is for manual invocation via `docker-compose run shell bash`.
  # It's handy to be able to mess around in a set up environment with the same dependencies and environment
  # as the rest of the services, but, we don't generally need it running in the background. So, this sets it all up
  # but we execute a command (true) that exits immediately to keep the container stopped by default.
  shell:
    <<: *tugboat_base
    command: "true"
    stdin_open: true
    ports: []
    volumes:
      - /Users/airhorns/Code/tugboat/tugboat:/root/catkin_ws/src/tugboat:delegated
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      <<: *tugboat_environment
      DISPLAY: $IP:0
      QT_X11_NO_MITSHM: '1'
      ROS_MASTER_URI: http://roscore:11311/
